import "./Stack.css";

export default function Stack() {
  return (
    <div className="stack">
      <h2>Languages and Tools</h2>
      <div className="icons">
        <a href="https://www.python.org/" target="_blank" rel="noreferrer">
          <img
            src="https://raw.githubusercontent.com/danielcranney/readme-generator/main/public/icons/skills/python-colored.svg"
            width="36"
            height="36"
            alt="Python"
          />
        </a>
        <a
          href="https://docs.microsoft.com/en-us/cpp/?view=msvc-170"
          target="_blank"
          rel="noreferrer"
        >
          <img
            src="https://raw.githubusercontent.com/danielcranney/readme-generator/main/public/icons/skills/cplusplus-colored.svg"
            width="36"
            height="36"
            alt="C++"
          />
        </a>
        <a
          href="https://docs.microsoft.com/en-us/dotnet/csharp/"
          target="_blank"
          rel="noreferrer"
        >
          <img
            src="https://raw.githubusercontent.com/danielcranney/readme-generator/main/public/icons/skills/csharp-colored.svg"
            width="36"
            height="36"
            alt="C#"
          />
        </a>
        <a
          href="https://developer.mozilla.org/en-US/docs/Web/JavaScript"
          target="_blank"
          rel="noreferrer"
        >
          <img
            src="https://raw.githubusercontent.com/danielcranney/readme-generator/main/public/icons/skills/javascript-colored.svg"
            width="36"
            height="36"
            alt="Javascript"
          />
        </a>
        <a
          href="https://www.typescriptlang.org/"
          target="_blank"
          rel="noreferrer"
        >
          <img
            src="https://raw.githubusercontent.com/danielcranney/readme-generator/main/public/icons/skills/typescript-colored.svg"
            width="36"
            height="36"
            alt="Typescript"
          />
        </a>
        <a href="https://jquery.com/" target="_blank" rel="noreferrer">
          <img
            src="https://raw.githubusercontent.com/danielcranney/readme-generator/main/public/icons/skills/jquery-colored.svg"
            width="36"
            height="36"
            alt="JQuery"
          />
        </a>
        <a
          href="https://developer.mozilla.org/en-US/docs/Glossary/HTML5"
          target="_blank"
          rel="noreferrer"
        >
          <img
            src="https://raw.githubusercontent.com/danielcranney/readme-generator/main/public/icons/skills/html5-colored.svg"
            width="36"
            height="36"
            alt="HTML5"
          />
        </a>
        <a
          href="https://www.w3.org/TR/CSS/#css"
          target="_blank"
          rel="noreferrer"
        >
          <img
            src="https://raw.githubusercontent.com/danielcranney/readme-generator/main/public/icons/skills/css3-colored.svg"
            width="36"
            height="36"
            alt="CSS3"
          />
        </a>
        <a href="https://reactjs.org/" target="_blank" rel="noreferrer">
          <img
            src="https://raw.githubusercontent.com/danielcranney/readme-generator/main/public/icons/skills/react-colored.svg"
            width="36"
            height="36"
            alt="React"
          />
        </a>
        <a href="https://sass-lang.com/" target="_blank" rel="noreferrer">
          <img
            src="https://raw.githubusercontent.com/danielcranney/readme-generator/main/public/icons/skills/sass-colored.svg"
            width="36"
            height="36"
            alt="Sass"
          />
        </a>
        <a href="https://tailwindcss.com/" target="_blank" rel="noreferrer">
          <img
            src="https://raw.githubusercontent.com/danielcranney/readme-generator/main/public/icons/skills/tailwindcss-colored.svg"
            width="36"
            height="36"
            alt="TailwindCSS"
          />
        </a>
        <a href="https://getbootstrap.com/" target="_blank" rel="noreferrer">
          <img
            src="https://raw.githubusercontent.com/danielcranney/readme-generator/main/public/icons/skills/bootstrap-colored.svg"
            width="36"
            height="36"
            alt="Bootstrap"
          />
        </a>
        <a href="https://www.mysql.com/" target="_blank" rel="noreferrer">
          <img
            src="https://raw.githubusercontent.com/danielcranney/readme-generator/main/public/icons/skills/mysql-colored.svg"
            width="36"
            height="36"
            alt="MySQL"
          />
        </a>
        <a
          href="https://www.microsoft.com/en-us/sql-server"
          target="_blank"
          rel="noreferrer"
        >
          <img
            src="https://www.svgrepo.com/show/303229/microsoft-sql-server-logo.svg"
            width="36"
            height="36"
            alt="Figma"
          />
        </a>
        <a
          href="https://flask.palletsprojects.com/en/2.0.x/"
          target="_blank"
          rel="noreferrer"
        >
          <img
            src="https://raw.githubusercontent.com/danielcranney/readme-generator/main/public/icons/skills/flask-colored.svg"
            width="36"
            height="36"
            alt="Flask"
          />
        </a>
        <a
          href="https://www.djangoproject.com/"
          target="_blank"
          rel="noreferrer"
        >
          <img
            src="https://raw.githubusercontent.com/danielcranney/readme-generator/main/public/icons/skills/django-colored.svg"
            width="36"
            height="36"
            alt="Django"
          />
        </a>
        <a
          href="https://dotnet.microsoft.com/en-us/"
          target="_blank"
          rel="noreferrer"
        >
          <img
            src="https://raw.githubusercontent.com/danielcranney/readme-generator/main/public/icons/skills/dot-net-colored.svg"
            width="36"
            height="36"
            alt=".NET"
          />
        </a>
        <a href="https://www.figma.com/" target="_blank" rel="noreferrer">
          <img
            src="https://raw.githubusercontent.com/danielcranney/readme-generator/main/public/icons/skills/figma-colored.svg"
            width="36"
            height="36"
            alt="Figma"
          />
        </a>
        <a href="https://www.docker.com/" target="_blank" rel="noreferrer">
          <img
            src="https://raw.githubusercontent.com/devicons/devicon/master/icons/docker/docker-original-wordmark.svg"
            width="36"
            height="36"
            alt="Figma"
          />
        </a>
        <a href="https://git-scm.com/" target="_blank" rel="noreferrer">
          <img
            src="https://www.vectorlogo.zone/logos/git-scm/git-scm-icon.svg"
            width="36"
            height="36"
            alt="Figma"
          />
        </a>
        <a href="https://postman.com" target="_blank" rel="noreferrer">
          <img
            src="https://www.vectorlogo.zone/logos/getpostman/getpostman-icon.svg"
            width="36"
            height="36"
            alt="Figma"
          />
        </a>
      </div>
    </div>
  );
}
